'use client';
import { use, useState, useEffect } from 'react';
import { analyzeHistory, type ProofPayMetrics } from '@/lib/history';

export default function VerifyPage({ params }: { params: Promise<{ wallet: string }> }) {
  const { wallet } = use(params);
  const [metrics, setMetrics] = useState<ProofPayMetrics | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    analyzeHistory(wallet)
      .then(setMetrics)
      .finally(() => setLoading(false));
  }, [wallet]);

  if (loading) return (
    <div className="flex min-h-screen items-center justify-center bg-background">
       <p className="animate-pulse font-bold text-primary">Verifying on-chain identity...</p>
    </div>
  );

  if (!metrics) return <div>Failed to load verification data.</div>;

  return (
    <main className="min-h-screen bg-background p-4 sm:p-8">
      <div className="mx-auto max-w-2xl rounded-3xl border border-border bg-card p-8 shadow-xl">
        <header className="mb-8 border-b border-border pb-8 text-center">
           <h1 className="text-sm font-black uppercase tracking-[0.2em] text-primary">Income Verification Report</h1>
           <p className="mt-2 text-xs text-secondary font-mono break-all">{wallet}</p>
        </header>

        <div className="grid grid-cols-2 gap-8 mb-12">
           <div className="text-center">
              <p className="text-[10px] font-bold uppercase text-secondary tracking-widest">Reliability Score</p>
              <p className="mt-2 text-5xl font-black text-primary">{metrics.reliabilityScore}</p>
           </div>
           <div className="text-center">
              <p className="text-[10px] font-bold uppercase text-secondary tracking-widest">Income Status</p>
              <p className={`mt-2 text-xl font-bold ${metrics.diversityScore === 'Low Risk' ? 'text-success' : 'text-warning'}`}>
                 {metrics.diversityScore}
              </p>
           </div>
        </div>

        <div className="space-y-6">
           <div className="flex justify-between border-b border-border pb-4">
              <span className="text-sm text-secondary">Verified Employer Records</span>
              <span className="text-sm font-bold text-foreground">{metrics.employerPayments.length} Payments</span>
           </div>
           <div className="flex justify-between border-b border-border pb-4">
              <span className="text-sm text-secondary">Total On-Chain Volume</span>
              <span className="text-sm font-bold text-foreground">{metrics.totalIncome.toLocaleString()} XLM</span>
           </div>
           <div className="flex justify-between border-b border-border pb-4">
              <span className="text-sm text-secondary">Activity Timeline</span>
              <span className="text-sm font-bold text-foreground">{metrics.monthlyHistory.length} Months Active</span>
           </div>
        </div>

        <div className="mt-12 rounded-2xl bg-accent p-6 text-center">
           <p className="text-xs font-bold text-primary uppercase">Blockchain Attestation</p>
           <p className="mt-2 text-[10px] leading-relaxed text-secondary">
              This report was generated by analyzing the immutable transaction history of the Stellar network. 
              The reliability score is derived from payment consistency, recurring employer records, and total volume.
           </p>
        </div>

        <footer className="mt-12 text-center">
           <button 
             onClick={() => window.print()}
             className="rounded-full bg-foreground px-6 py-2 text-xs font-bold text-white shadow-lg hover:bg-foreground/90 print:hidden"
           >
             Print Verification
           </button>
           <p className="mt-6 text-[10px] text-secondary">ProofPay · Powered by Stellar Testnet</p>
        </footer>
      </div>
    </main>
  );
}
